language: node_js
node_js:
- "--lts"
os:
- linux
- osx
install: npm install
script:
- gulp default
- ls html
deploy:
  provider: firebase
  token:
    secure: Rsmy78VAz49JDqZvdpV/Uz7FGAQUegMLXGbrZujDysUXtrSDFkYha4LrlDsmmU2do1oQwG809gVz3pzGEK+MZ+M8QMU8oNj0CZ4ohf6wZyDPH0T8XnbKIOY4mg2QyMYMs7C/Ne1yHQaclme2+JGjAmZodZgYcIqDX2zikRQ+/V7nBEH1974yHdgA1dq6Vr2aH8UdGOPU5FvkI+DiXlTzJH+x5OKIvhy4WNaAqWi/2hIxdnPD2TSduXTt2vFNO98lReiZLDhu+O6Hmmmq9iqo9u20PDzYPc77gv1ybgPGXGDRffspZ8DbT9TbTBff20+Qb5mENdfTb9ronTlfBU+k+j0J2caVeXURy5v7jIhcynCWUG7veUjQtJpvxN/dgezy8DTCTEmOTpsFeH7JH07B/Oh+7HKF3UDpJMv5sbM69g2EmjkIPkfWAcxXNH4yGF/PK1S7b8PjLBLJcDJ2lRMgllRKsG6fmfiZkQj2rhhH2w6uD6qUU5D/SoFbphyuhV3DLGHaEOI8zUccdkv3vxBVlq3//Q2zHuKpTAsK4AXM09oSHvubhoAZVTTXRbE0qATPnb7KDPiek3PblqlJJN5OGQ2TEE7ESMxwjBV7RC23qXzQBvUXu05xclaX0GuEqCTQXxnrYp1zMbsHuCCWKN3NQKDA4Cv+QUzUnSQ1dER2L+E=
  project: "matteo-bucci"
  skip_cleanup: true
  local-dir: html