language: node_js
node_js:
- "--lts"
os:
- linux
- osx
install: npm install
script:
- gulp default
deploy:
  provider: gcs
  access_key_id: GOOGPXNXJNYZOYFH2WIWPYA5
  secret_access_key:
    secure: FP/+2Uh3dZ88TFz8b7FfNOUk8Oj5j0NEPs5pCD/gityjHDEwdxWtx3l1sPQeSQoV1CAw4cSkTTjxXVOulnzRYE/CSpeWDA10c0v9q8mrUz66rF6B8CI4BC1XEMFd2FzEnzWS8rr6oDawFZUo8PK7DPN/NoZgy4roKuGSPhTwCCn6+ZBNif3MYhz3930cRPV/tFMflXOF0TCKWVzc88o2egCCB0HNUA1Pi8jhjnRPgLXZmhyxvlohi8XBhIHvlhSjeAH+kW36MotFNH9ADHGWSs5d7f9ksxugxyRLErvN8mjAPXUzbZ1RgAQBrxqgmD9DxcqQk0gq3MFPBU3y1+6/p/J2d1+l4y6nwdtJcywB3A6HngaEAsXxAP7Xb/D//ejQkHDzzG94F2S0cAkwQ65CmnsPFSah9pX1+SLFdtu0zqBon59lBWv6Zh18TJpbe4QTu8HEIpQS0TX37s9QT9X3So1SYz8SFmmhaNp4A9Av4FqjIeolQq9A4aCboQB6TxjUALf/fnzvDVDFdUdAFAboN61OfpELrSUfGmHFQ4HBt4k2//2FCI3o+HIb21QHOrllTxX7SK4uXCg5S2qs8MpHDO1M5gUpom4N308WuDz4YMhLRJmEhrEld18VvHUoVJlLpH1IbniswNTbQYIh/2MhpWkSupIM0BVumk26bISmQD8=
  bucket: www.matteobucci.it
  local-dir: html
  on:
    repo: matteobucci/matteo-website
