language: node_js
node_js:
- "--lts"
os:
- linux

install:
  - npm install -g firebase-tools
  - npm install
script:
- gulp default
- ls html

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

branches:
  only:
  - master